# Project Information
site_name: "Pycord Developer Network"
site_description: Documentation, Guides & More for Pycord Developers.
repo_url: https://github.com/pycord/pycord-v3
repo_name: pycord/pycord-v3
copyright: "©2022 VincentRPS & PDN Contributors"
docs_dir: developer
watch: [pycord]

# Navigation Tree
nav:
  - Home: index.md
  - API Reference:
    - Apps: api/apps.md
    - Assets: api/assets.md
    - Channels: api/channels.md
    - Events: api/events.md
    - Guild: api/guild.md


# Theme Configuration
theme:
  name: material
  locale: en

  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top

  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/logo.png
  logo: assets/logo.png
  icon:
    repo: fontawesome/brands/github
  highlightjs: true

# Extensions
markdown_extensions:
  - toc:
      permalink: true

# Plugins
plugins:
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            docstring_style: google
            inherited_members: true
          rendering:
            heading_level: 2
            show_root_full_path: false
            show_root_heading: true
            show_signature_annotations: true
            show_source: false
  - search

# Extra Customization
extra:
  generator: false

extra_css:
  - assets/theme.css
